# Generated by Django 4.2.7 on 2023-11-17 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meeting_rooms_booking', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meetingroom',
            name='is_available',
            field=models.BooleanField(default=False),
        ),
    ]
