# Generated by Django 4.2.7 on 2023-11-18 05:56

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meeting_rooms_booking', '0003_meetingroom_created_at_meetingroom_updated_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='BookingHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room_name', models.CharField(max_length=255)),
                ('user_name', models.CharField(max_length=255)),
                ('booking_date', models.DateTimeField(default=datetime.datetime(2023, 11, 18, 11, 26, 4, 777177))),
            ],
        ),
    ]
