# Generated by Django 4.2.7 on 2023-11-18 05:57

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meeting_rooms_booking', '0004_bookinghistory'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookinghistory',
            name='booking_date',
            field=models.DateTimeField(default=datetime.datetime(2023, 11, 18, 11, 27, 30, 688831)),
        ),
    ]
