# Generated by Django 4.2.7 on 2023-11-18 06:26

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meeting_rooms_booking', '0005_alter_bookinghistory_booking_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookinghistory',
            name='booking_date',
            field=models.DateTimeField(default=datetime.datetime(2023, 11, 18, 11, 56, 33, 659107)),
        ),
    ]
