# Generated by Django 4.2.7 on 2023-11-18 06:53

import datetime
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('meeting_rooms_booking', '0006_alter_bookinghistory_booking_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='meetingroom',
            name='booking_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='bookinghistory',
            name='booking_date',
            field=models.DateTimeField(default=datetime.datetime(2023, 11, 18, 12, 23, 12, 844434)),
        ),
    ]
