# Generated by Django 4.2.7 on 2023-11-18 07:19

import datetime
from django.db import migrations, models
import meeting_rooms_booking.models


class Migration(migrations.Migration):

    dependencies = [
        ('meeting_rooms_booking', '0008_alter_bookinghistory_booking_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookinghistory',
            name='booking_date',
            field=models.DateTimeField(default=datetime.date(2023, 11, 18)),
        ),
        migrations.AlterField(
            model_name='meetingroom',
            name='booking_date',
            field=models.DateTimeField(validators=[meeting_rooms_booking.models.validate_future_date]),
        ),
    ]
